#spring:
#  datasource:
#    url: jdbc:mysql://prod-db:3306/courseweb_prod
#    username: prod_user
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: validate
#server:
#  port: 8082
#logging:
#  level:
#    root: INFO
